services:
  pg:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=rag
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # ollama:
  #   image: ollama/ollama:latest
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama:/root/.ollama
  #   pull_policy: always

  rag-cli:
    build: ./rag-cli
    depends_on:
      - pg
    #   - ollama
    environment:
      - PGHOST=pg
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=rag
      - OLLAMA_HOST=http://ollama:11434
      - SCRAPE_URL=${SCRAPE_URL}
    volumes:
      - rag-service:/data
    #   - ./docs:/docs:ro
    #   - ./rag-cli:app
    # command: ["bash", "-lc", "python app.py"]

volumes:
  pgdata:
  ollama:
  rag-service: