services:
  pg:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=rag
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    container_name: pgvector
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    environment:
      - LLM_MODEL=${LLM_MODEL}
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./ollama_entrypoint.sh:/ollama_entrypoint.sh
    container_name: ollama
    pull_policy: always
    restart: unless-stopped
    entrypoint: ["/usr/bin/bash", "/ollama_entrypoint.sh"]

  rag-cli:
    build: ./rag-cli
    depends_on:
      - pg
      - ollama
    environment:
      - PGHOST=pg
      - PGUSER=${POSTGRES_USER}
      - PGPASSWORD=${POSTGRES_PASSWORD}
      - PGDATABASE=rag
      - OLLAMA_HOST=http://ollama:11434
      - SCRAPE_URL=${SCRAPE_URL}
    ports:
      - "8000:8000"
      - "7860:7860"
      - "7861:7861"
    volumes:
      - rag-service:/data
    container_name: rag_service
    restart: unless-stopped

volumes:
  pgdata:
  ollama_data:
  rag-service: